apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: openproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: memcached
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: openproject
spec:
  type: ClusterIP
  selector:
    app: cache
  ports:
  - port: 11211
