apiVersion: v1
kind: Secret
metadata:
  name: environment
  namespace: openproject
type: Opaque
stringData:
  RAILS_CACHE_STORE: "memcache"
  OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
  DATABASE_URL: "postgres://postgres:keyboardcat@postgres/openproject"
  USE_PUMA: "true"
  # set to true to enable the email receiving feature. See ./docker/cron for more options
  IMAP_ENABLED: "false"
